apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-dotnet-deployment
  labels:
    app: loan-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-dotnet
  template:
    metadata:
      labels:
        app: loan-dotnet
    spec:
      containers:
      - name: loan-dotnet
        image: ajs3ra8/loan-app-dotnet:7
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: loan-dotnet-service
spec:
  type: NodePort
  selector:
    app: loan-dotnet
  ports:
    - port: 5000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5000

