name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "original_manifest/**"
      - "manifests/**"
      - "README.md"

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ajs3ra8/loan-app-dotnet:${{ github.run_number}}

    - name: Push the Docker image to Docker Hun
      run: docker push ajs3ra8/loan-app-dotnet:${{ github.run_number}}


    - name: Checkout source code
      uses: actions/checkout@v4   
      with:
          password: ${{ secrets.TOKEN }}

     
    - name: Create manifest
      run: |
          mkdir -p manifests
          cp original_manifest/* manifests/
          sed -i "s/IMAGE_TAG/${{ github.run_number }}/g" ./manifests/deployment.yaml

          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git add manifests/deployment.yaml
          git commit -m "Add Kubernetes manifests"
          git push

      
